# Generated by Django 4.1 on 2024-08-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
    ]
